### ISSUE TITLE
範囲外の場合のテストも追加してください

### ISSUE THREAD

**Issue by amapyon** [ryokryok999/pg_ex01_2#1]
https://github.com/ryokryok999/pg_ex01_2/blob/871cde2f3397cfa758e8350657b4760d6fccb7c3/src/pg_ex01_2/RomanNumTest.java#L7

仕様の

> 0以下、21以上の場合は、"変換できません"という文字列を返すこと

のテストケースも追加してください。

**Comment by ryokryok999** [comment]
ご指摘、ありがとうございます。

標準出力の内容をテストする方法を調べたのですが、
http://d.hatena.ne.jp/hyuki/20060818/junit
など、とても難しそうでしたので、

今回は、シンプルに、0以下、21以上の場合は、
戻り値がNullになるので、それをテストとして作成しました。

お手数おかけいたしますが、ご確認よろしくお願いいたします。

**Comment by amapyon** [comment]
テストの対象は、メソッドのinput/outputのみですので、標準出力は考えなくてよいです。

"変換できません"という**文字列を返すこと**を確認してみてください。
表明は、以下のようになります。

assertEquals("変換できません", RomanNum.convertRomanNum(0));

**Comment by amapyon** [comment]
修正を確認しました。
